### ISSUE TITLE
Use in Blazor?

### ISSUE THREAD

**Issue by lonix1** [dmester/jdenticon-net#12]
Does someone know how to use this in blazor wasm?

Ideally, to generate the image and insert it into the DOM, without an intermediate image file.

**Comment by dmester** [comment]
Try to install the [Jdenticon-net](https://www.nuget.org/packages/Jdenticon-net) package. Then you can generate an icon as SVG and insert it on your page.

Example:
```razor
@using Jdenticon

<h1>Jdenticon using Blazor WASM</h1>

@icon

@code {
    private MarkupString icon;

    protected override void OnInitialized()
    {
        var userId = "user 123";

        icon = (MarkupString)Identicon
            .FromValue(userId, size: 200)
            .ToSvg();
    }
}
```

The code above worked when I tested it with .NET 6. It will likely not work with Blazor WASM + .NET 5 due to [limitations in the System.Security.Cryptography namespace](https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly).

**Comment by dmester** [comment]
It uses the crypto namespace for hashing the input values.

Note that the limitations are only in .NET 5. If you use .Net 6 it should work. See working example in my previous comment. 

There is no plan fixing the library for .Net 5 since it is already out of support my Microsoft.

**Comment by dmester** [comment]
I'm glad to hear it worked.

Both libraries can generate vector icons as SVG (see [jdenticon.toSvg](https://jdenticon.com/js-api/M_jdenticon_toSvg.html) in JS), and raster icons, in JS on a canvas, and in .NET as a PNG image.
